name: promote
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ros-esm-dependencies-diff-generator version to promote'
        required: true
        default: latest
        type: choice
        options:
          - latest

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/promote.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      snap: ros-esm-dependencies-diff-generator
      from-channel: '${{ inputs.version }}/candidate'
      to-channel: '${{ inputs.version }}/stable'
